### ISSUE TITLE
Please create a Google-free build target

### ISSUE THREAD

**Issue by marmistrz** [fastbootmobile/encore#24]
Your app depends on non-free `com.google.android.gms:play-services-cast` library. Not all Android users want to have Google's proprietary services on their phones. This functionality is not provided by microG either.

Please create a build flavor which is stripped of the Play Services dependencies, and thus, Chromecasting functionality.

**Comment by xplodwild** [comment]
We are working on reengineering parts of the app, we will look into that

**Comment by ddevault** [comment]
:+1: I also don't run google play services

**Comment by rocketinventor** [comment]
@marmistrz Why not contact micro-g about that? There are many other apps that utilize it.

**Comment by marmistrz** [comment]
>@marmistrz Why not contact micro-g about that? There are many other
>apps that utilize it.

microG doesn't support cast as for now. There's a bounty for it, but no one has taken it yet.

**Comment by ddevault** [comment]
I think it's okay for some features not to work if google play services is unavailable.

**Comment by marmistrz** [comment]
Yes, but one should be able to easily build the app without gms.

Even if the target device doesn't have gms, building with gms enabled still causes proprietary code to be injected afaik.
--
Marcin

**Comment by xplodwild** [comment]
We are currently working on rewriting Encore from the ground up to address a few issues at the core of the experience. We will consider removing all the Google-proprietary dependencies from the build.
