### ISSUE TITLE
error: cannot find symbol class APIKeys

### ISSUE THREAD

**Issue by eadward** [fastbootmobile/encore#27]
Hi,

I am trying to compile Encore, but I am getting the following error:

> Error:(34, 44) error: cannot find symbol class APIKeys

due to 

> import com.fastbootmobile.encore.api.common.APIKeys;

in the EchoNest.java file

Same error a bit after in the same file

> mEchoNest = new EchoNestAPI(APIKeys.KEY_ECHONEST);

I would be very thankful for any help with this.

Cheers.

**Comment by xplodwild** [comment]
See https://github.com/fastbootmobile/encore/blob/master/src/main/java/com/fastbootmobile/encore/api/common/APIKeys.java.template

**Comment by eadward** [comment]
thank you! I found the problem and solved. For some reason that file was not being synced.
