### ISSUE TITLE
Lack of TV control support

### ISSUE THREAD

**Issue by simonsickle-old** [fastbootmobile/encore#6]
This was tested on a fire tv, but, it appears that the UI does not like to be ran with a standard remote control on these tv boxes. Overall, it works on the tv but needs a mouse/keyboard to work properly.

Would it be welcome for some patches regarding tv support? If so, I will work on this.

**Comment by jerdog** [comment]
Feel free to contribute and help with the app. Thanks mate!

**Comment by xplodwild** [comment]
We have a leanback UI on Android TV - is there some way you could try to use that on your Fire TV?
